name: Amr Abed
description: Amr Abed
url: "https://amrabed.me"
baseurl: "/"

google_analytics: UA-87254560-1

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE
- README.md
- CNAME
- docker-compose.yml
- sonar-project.properties