name: Lint code

on:
  push:
    paths: ['next/**']
  workflow_call:

defaults:
  run:
    working-directory: next

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: make install
            - name: Format and lint
              run: make lint