name: Lint code

on:
  push:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: mise run install
      - name: Format and lint
        run: mise run lint
