name: Deploy to Firebase

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  deploy:
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Authenticate to Firebase
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d
      - name: Deploy to Firebase
        run: mise run deploy