name: Deploy to Firebase

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - name: Install dependencies
        run: mise run install
      - name: Install Firebase
        run: mise run firebase
      - name: Deploy to Firebase
        run: mise run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
