name: Verify code

on:
  push:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: Verify project
        run: mise run verify
